[package]
name = "aix-connector"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
aix-core = { path = "../aix-core" }
aix-permission = { path = "../aix-permission" }
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
url.workspace = true
